[package]
name = "actix-ap-demo"
version = "0.1.0"
authors = ["Riley Trautman <asonix.dev@gmail.com>"]

[dependencies]
actix = "0.4"
actix-web = "0.3"
env_logger = "0.5"
futures = "0.1"
log = "0.4"

[dev-dependencies]
tokio-timer = "0.1"
